blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),    
    path('search/', views.post_search, name='post_search'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                        name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

def upload_locatio(instance, filename):
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "posts/%s/%s" %(new_id, filename)

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    description = models.TextField()                          
    body = models.TextField()
    image = models.ImageField(upload_to="upload_locatio")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])

blog/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from .models import Post
from .forms import SearchForm
from taggit.models import Tag


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'posts': posts,
                  'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]


    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                  'similar_posts': similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blog/post/list.html'

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ar">
<head>
  {% if title %}
    <title>Django Blog - {{ title }}</title>
    {% else %}
    <title>11010 دت كوم</title>
  {% endif %}
  
  <!-- Meta -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Blog Template">
  <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    

  <link rel="shortcut icon" href="favicon.ico"> 

  <!-- FontAwesome JS-->
  <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>

  <link href="{% static 'css/theme-1.css' %}" rel="stylesheet">  
  <link rel="stylesheet" href="{% static 'css/ar.css' %}">

  <style>
    p{
           text-align: right;
           direction: rtl;
       }
         blockquote{
             background: #f4f4f4;
             border: 1px solid rgb(245, 242, 242);
             border-left: 3px solid #f36d33;
             color: #666;
             page-break-inside: avoid;
             font-family: monospace;
             font-size: 15px;
             line-height: 1.6;
             margin-bottom: 1.6em;
             max-width: 100%;
             overflow: auto;
             padding: 1em 1.5em;
             display: block;
             word-wrap: break-word;
             direction: ltr !important;
             text-align: left !important;
             font-family: 'Courier New', Courier, monospace;
         }

        
 </style>
</head>
<body>
    <header class="header text-center">	    
        <h1 class="blog-name pt-lg-4 mb-0"  style="direction: rtl;">مدونة جانجو العربية</h1>
      
        <nav class="navbar navbar-expand-lg navbar-dark" >
         
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column" >
                <div class="profile-section pt-3 pt-lg-0">
                      <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'assets/images/profile.png/'%}" alt="image" >			

                      <div class="bio mb-3">مرحبا أنا راضي عباد مطور ويب وكنت مطورًا رئيسيًا في حياتي الماضية ، والآن أستمتع بتدريس الدورات.<br><a href="#">معرفة المزيد عني</a></div><!--//bio-->
                            
                      <ul class="social-list list-inline py-3 mx-auto">
                          <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                          <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                          <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                          <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
                          <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                      </ul><!--//social-list-->
                      <hr> 
                </div><!--//profile-section-->
           
                <br>
                <br>  
                <div class="my-2 my-md-3">    
                    <a class="btn btn-primary" href="#" >تـواصـل مـعـنـا</a>
                </div>

                <!-- Her Nav small scran -->
            </div>
        </nav>  
    </header>

<div class="main-wrapper">
  <nav class="navbar navbar-expand-md  bg-steel color-my" style="background-color:  rgba(95,203,113,0.25);">
      <!-- <div class="container"> -->
        <a class="navbar-brand" href="#">جانجو العربية</a>
        </button>
        <div class="navbar-collapse">       
          <!-- Navbar Right Side -->
          <div class="navbar-nav mr-auto">
            
              <a class="nav-item nav-link " style=" font-size: large;" href="#">كورسات Django</a>
              <a class="nav-item nav-link  " style="font-size: large;"href="#">كورسات Python</a>
              <a class="nav-item nav-link  btn-primary pr-2" style="border-radius: 3px;" href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>

            </div>
        </div>
      <!-- </div> -->
  </nav>    
  {% block content %}
  
  
  {% endblock %}

  
  {% show_latest_posts 2 %}
  
{% block footer %}     
<footer class="footer text-center  theme-bg-dark">

  <nav class="navbar navbar-expand-md  bg-steel color-my" style="background-color:  rgba(95,203,113,0.25);">

      <a class="navbar-brand" href="#">جانجو العربية</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="#">الرئيسية</a>
          <a class="nav-item nav-link" href="#">عن المدونة</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#"> أنشاء منشور جديد </a>
            <a class="nav-item nav-link" href="#">البروفايل</a>
          {% endif %}
        </div>
      </div>

  </nav>        

</footer>
{% endblock %}
</div>
<!-- Javascript -->          
<script src="{% static 'assets/plugins/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'assets/plugins/popper.min.js' %}"></script> 
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script> 

</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<style>
.single-blog-item {
  border: 1px solid #dfdede;
  box-shadow: 2px 5px 10px #dfdede;
  margin: 15px auto;
  padding: 5px;
  position: relative;
}
.blog-content {
  padding: 15px;
}
.blog-content h4 {
  font-size: 16px;
  font-weight: 500;
  margin-bottom: 10px;
  text-transform: uppercase;
}
.blog-content h4 a{
	color:#777;
	}
.blog-content p{
  color: #999;
  font-size: 14px;
  font-weight: 300;
  line-height: 1.3333;
}
.blog-date{
	}
.blog-date {
    position: absolute;
	  background: #337ab7;
    top: 35px;
    left: 5px;
    color: #fff;
    border-radius: 0 25px 25px 0;
    padding: 5px 15px;
    font-weight: 700;
}
.more-btn {
  background: #337ab7;
  border-radius: 2px;
  display: block;
  height: 30px;
  line-height: 30px;
  margin: 30px auto auto auto;
  text-align: center;
  width: 110px;
  color: #f1f1f1;
}</style>
<div class="container">
  <h3 class="heading">اخر الدروس</h3>
  <hr class="mt-4">
  <div class="row mb-5">
    {% for post in latest_posts %}

      <div class="col-md-6">
         <div class="single-blog-item">
                 
                  <div class="blog-content">
                      <h4><a href="">{{post.title}}</a></h4>
                      <div class="intro" style="direction: rtl; text-align: right;">{{post.description|truncatewords_html:20}}.</div>
                      <a class="more-link" href="{{ post.get_absolute_url }}">اقراء المزيد &larr;</a>
                        <p class="tags " style="float: right; direction: rtl; text-align: right;">
                          {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                              {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                          {% endfor %}
                        </p>
                  </div>
              </div>
       </div>
       
    {% endfor %}
   
  </div>
</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <!-- title page subscrib button -->
    <section class="cta-section theme-bg-light py-5">
      <div class="container text-center">
          <h2 class="heading">  مدوتنة جانجو العربي - لتعلم جانجو باللغة العربية</h2>
          <div class="intro">مرحبا بك في مدونتي!! أشترك من أجل الحصول أخر دورسي</div>
          <div class="intro">امتلك في مدونتي  {% total_posts %} من الدروس .</div>

          <form class="signup-form form-inline justify-content-center pt-3">
              <div class="form-group">
                  <label class="sr-only" for="semail">أدخل بريدك الإلكتروني</label>
                  <input type="email" id="semail" name="semail1" class="form-control ml-md-1 semail" placeholder="أدخل بريدك الإلكتروني">
              </div>
              <button type="submit" class="btn btn-primary">أشتراك</button>
          </form>
      </div><!--//container-->
  </section>
  <!-- title page //////// -->
  <section class="blog-list px-3 py-5 p-md-5">
    <div class="container">
        {% if tag %}
          <h2 class="my-5"> كورسات خاصة بــ "{{ tag.name }}"</h2>
        {% endif %}

        {% for post in posts %}
            <div class="item mb-5">
                <div class="media">
                    <img class="ml-3 img-fluid post-thumb d-none d-md-flex" src="{{post.image.url}}" alt="image">
                    <div class="media-body">
                        <h3 class="title mb-1"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        
                        <div class="meta mb-1"><span class="date">نشر قبل {{ post.publish|timesince }} الماضية</span></div>
                        <div class="intro">{{ post.description|truncatewords_html:30 }}</div>
                        <a class="more-link" href="{{ post.get_absolute_url }}">اقراء المزيد &larr;</a>
                        <p class="tags " style="float: left;">
                          {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                              {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                          {% endfor %}
                        </p>
                    </div><!--//media-body-->
                </div><!--//media-->
            </div><!--//item-->
        {% endfor %}

        {% include "pagination.html" with page=posts %}

        
    </div>
</section>
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
  <nav class="blog-nav nav nav-justified my-5">
            {% if page.has_next %}
                <a class="nav-link-prev nav-item nav-link d-none rounded-left " href=>السابق<i class="arrow-prev fas fa-long-arrow-alt-right"></i></a>
                <a class="nav-link-next nav-item nav-link rounded ml-2" href="?page={{ page.next_page_number }}">التالي<i class="arrow-next fas fa-long-arrow-alt-left"></i></a>
            {% endif %}

            {% if page.has_previous %}
                <a class="nav-link-prev nav-item nav-link rounded-left" href="?page={{ page.previous_page_number }}">السابق<i class="arrow-prev fas fa-long-arrow-alt-right"></i></a>
                
            {% endif %}    
        </nav>